version: '3.8'

services:
  nginx:
    image: zarak.fr:8092/cache/library/nginx:1.21-alpine
    depends_on:
      - web
      - worker
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
  
  worker:
    build: ./worker
    depends_on:
      - redis

  redis:
    image: zarak.fr:8092/cache/library/redis:7.0-alpine

  web:
    build: ./web
  
 
